[project]
name = "ollama-model-scrapper"
version = "0.1.0"
description = "Quick and Dirty Ollama model list scrapper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "pydantic>=2.11.9",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
